# Generated by Django 4.2.25 on 2025-10-27 06:12

from django.db import migrations, models
import judge.models.submission


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0151_add_problem_package_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='package_checksum',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='package checksum'),
        ),
        migrations.AddField(
            model_name='submission',
            name='package_file',
            field=models.FileField(blank=True, null=True, upload_to=judge.models.submission.submission_directory_file, verbose_name='submission package file'),
        ),
        migrations.AddField(
            model_name='submission',
            name='package_id',
            field=models.CharField(blank=True, help_text='External JUDGE package identifier', max_length=64, null=True, verbose_name='package id'),
        ),
        migrations.AddField(
            model_name='submission',
            name='package_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='package size (bytes)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='package_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='package uploaded at'),
        ),
        migrations.AddField(
            model_name='submission',
            name='package_version',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='package version'),
        ),
    ]
