# Generated by Django 4.2.25 on 2025-10-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0153_add_result_event_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemdata',
            name='package_path',
            field=models.CharField(blank=True, help_text='Reference path or URL to the problem package (preferred)', max_length=500, null=True, verbose_name='package path'),
        ),
    ]
